name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "d439927da7334d23a8b6320b1bc693b7" }
]
account_id = "kattumi@gmail.com"
[triggers]
crons = [ ]
